name: hello world
on: 
  workflow_dispatch:
    inputs:
      firstname:
        description: What is your name
        required: false
        default: Max
jobs:
  job-one:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
